## Сводная таблица Комиссия\Рейтинг. Тестовое задание

Необходимо построить сводную таблицу:
  -  По оси X рейтинг займа
  -  По оси Y комиссия
  -  Сводные данные по сумме займа

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('test.csv')

Для составление таблицы нужна предобработка данных.

- В 5 столбцах тип не соответствует данным.
- Есть лишние символы, которые необходимо удалить перед преобразованием типов.

In [3]:
columns = ['Loan issued', 'Comission, %', 'Earned interest',
       'Unpaid,  full amount', 'EL']

for column in columns:
    data[column] = data[column].apply(lambda x: x.translate({ord(i): None for i in ['₽', '%']}))
    data[column] = data[column].apply(lambda x: x.replace(',', '.'))
    data[column] = data[column].apply(lambda x: x.replace(u'\xa0', ''))
    
    data[column] = pd.to_numeric(data[column], errors='coerce')

In [4]:
columns = ['Comission, %', 'EL']
data[columns] = data[columns]/ 100
data.head()

,Loan issued,Рейтинг,"Comission, %",Earned interest,"Unpaid, full amount",EL,учредителю подсказывают / на ВИ другой человек,"На ВИ присутствует ""сотрудник"", в тч за кадром, который отвечает на вопросы","""Сотрудник"" отвечает на вопросы. ГД/учредитель молчит или отвечает редко.",В компании была смена учредителя,...,"Не знает наценку (рентабельность, прибыль)","Не знает кредиторов ), в тч объем обязательств",Нерелевантный опыт работы,Нелогичный выбор сферы бизнеса,За ответом на вопросы 10-14 просит обратиться к сотруднику,Данные предоставленные заемщиком разнятся с действительностью > 50%,"Есть ""партнер"", который официально не оформлен","Не потребовалось денег для начала бизнеса, тк были договоренности с поставщиками","Офис находится в здании партнера/друга/родственника, аренду не платит.",Заемщик от партнера и был подготовлен к ВИ
0,3170000,7,0.0530,211051,862850,0.015,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,500000,17,0.0650,39518,289518,0.100,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
2,11600897,9,0.0450,537680,9567386,0.015,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,5250000,13,0.0450,233022,2858022,0.015,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,3000000,8,0.0375,216485,0,0.000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Составим сводную таблицу и заполним образовавшиеся пропуски.

In [5]:
pivot = data.pivot_table(
    index=['Comission, %'], 
    columns='Рейтинг', 
    values='Loan issued', 
    aggfunc='sum')

In [6]:
pivot

Рейтинг,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
"Comission, %",,,,,,,,,,,,,,,,,,
0.0200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5500000.0,NaN,NaN,NaN,1836735.0,NaN,NaN,NaN,NaN,NaN
0.0213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000000.0,NaN,NaN,NaN,NaN,NaN,NaN
0.0215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8700000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.0224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8640000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.0225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800000.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.0680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1175000.0,NaN,NaN,2000000.0,3000000.0,NaN,NaN,NaN,NaN,3000000.0,NaN
0.0690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.0700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2790000.0,NaN,NaN,NaN,NaN
0.0780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000000.0,NaN,4000000.0,NaN,NaN,NaN,NaN,NaN,1700000.0
0.0830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7000000.0,1000000.0,NaN,1030000.0,NaN

In [7]:
pivot.fillna(0)

Рейтинг,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
"Comission, %",,,,,,,,,,,,,,,,,,
0.0200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5500000.0,0.0,0.0,0.0,1836735.0,0.0,0.0,0.0,0.0,0.0
0.0213,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3000000.0,0.0,0.0,0.0,0.0,0.0,0.0
0.0215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8700000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.0224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8640000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.0225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,800000.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.0680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1175000.0,0.0,0.0,2000000.0,3000000.0,0.0,0.0,0.0,0.0,3000000.0,0.0
0.0690,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.0700,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2790000.0,0.0,0.0,0.0,0.0
0.0780,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2000000.0,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,1700000.0
0.0830,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7000000.0,1000000.0,0.0,1030000.0,0.0

В данных по комиссии достаточно большой разброс значений, если данные по каждому значению комиссии не так важны, можно округлить значения до выбранного знака.

In [8]:
data['Comission_round, %'] = round(data['Comission, %'],2)

In [9]:
data.head(10)

,Loan issued,Рейтинг,"Comission, %",Earned interest,"Unpaid, full amount",EL,учредителю подсказывают / на ВИ другой человек,"На ВИ присутствует ""сотрудник"", в тч за кадром, который отвечает на вопросы","""Сотрудник"" отвечает на вопросы. ГД/учредитель молчит или отвечает редко.",В компании была смена учредителя,...,"Не знает кредиторов ), в тч объем обязательств",Нерелевантный опыт работы,Нелогичный выбор сферы бизнеса,За ответом на вопросы 10-14 просит обратиться к сотруднику,Данные предоставленные заемщиком разнятся с действительностью > 50%,"Есть ""партнер"", который официально не оформлен","Не потребовалось денег для начала бизнеса, тк были договоренности с поставщиками","Офис находится в здании партнера/друга/родственника, аренду не платит.",Заемщик от партнера и был подготовлен к ВИ,"Comission_round, %"
0,3170000,7,0.0530,211051,862850,0.015,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.05
1,500000,17,0.0650,39518,289518,0.100,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0.06
2,11600897,9,0.0450,537680,9567386,0.015,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0.04
3,5250000,13,0.0450,233022,2858022,0.015,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0.04
4,3000000,8,0.0375,216485,0,0.000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.04
5,4300000,9,0.0600,143563,0,0.000,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.06
6,1000000,16,0.0650,69823,741372,0.300,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0.06
7,1020000,14,0.0650,22902,964508,0.015,0,1,0,0,...,0,1,0,1,0,0,0,1,0,0.06
8,6000000,13,0.0550,223228,4446456,0.015,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0.06
9,800000,16,0.0500,51566,451566,0.015,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.05

In [10]:
pivot = data.pivot_table(
    index=['Comission_round, %'], 
    columns='Рейтинг', 
    values='Loan issued', 
    aggfunc='sum')

In [11]:
pivot.fillna(0)

Рейтинг,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
"Comission_round, %",,,,,,,,,,,,,,,,,,
0.02,0.0,0.0,0.0,0.0,0.0,3000000.0,0.0,11996427.0,14140000.0,0.0,0.0,3800000.0,1836735.0,0.0,0.0,0.0,0.0,0.0
0.03,0.0,0.0,14800000.0,26070000.0,10200000.0,4000000.0,4500000.0,0.0,17000000.0,7990000.0,23700000.0,16560000.0,6036310.0,0.0,0.0,3500000.0,600000.0,0.0
0.04,0.0,0.0,5000000.0,30852000.0,6500000.0,14500000.0,41575000.0,39000000.0,38220897.0,41594357.0,26980000.0,27533825.0,14910000.0,12780000.0,12930000.0,12860000.0,1850000.0,1300000.0
0.05,0.0,0.0,0.0,3590000.0,13550000.0,21930000.0,78037238.0,53708076.0,10500000.0,76842440.0,55220059.0,33815781.0,30804871.0,29880000.0,10550000.0,11850000.0,3650000.0,1500000.0
0.06,1500000.0,4300000.0,1000000.0,10000000.0,15990000.0,12427736.0,29990000.0,30190000.0,60169956.0,60385005.0,49474958.0,50315267.0,122425669.0,65336107.0,86642611.0,23900690.0,35550000.0,16540000.0
0.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1175000.0,0.0,0.0,4000000.0,3000000.0,0.0,2790000.0,0.0,4530000.0,4090000.0,0.0
0.08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2000000.0,0.0,4000000.0,0.0,7000000.0,1000000.0,0.0,1030000.0,1700000.0